spring:
  banner:
    location: classpath:banner.txt
  web:
#    resources:
#      add-mappings: true
#      static-locations: [classpath:/hello] #自定义静态资源文件
#  mvc:
#    static-path-pattern: /res/**  #前缀会影响 welcome 和favicon.ico